### PR TITLE
Create soso

### PR DESCRIPTION
**Pull request by nooooof**

### CODE REVIEW

**Comment by nooooof** [comment]
help

**Comment by AhmadGhadiri** [comment]
what is the problem you have?

**Comment by nooooof** [comment]
When I try execute the file 
The message file array copy .hex not found
My send that file 
Thank you 

‏‫من جهاز الـ iPhone الخاص بي‬

**Comment by AhmadGhadiri** [comment]
Oh I see. This is the input file to Tomasulo program which is a .hex file including the list of commands. Unfortunately I wrote this program some years ago and don't have access to any examples. You probably can create some files yourself.

**Comment by nooooof** [comment]
Ok thank you very mush for help 

‏‫من جهاز الـ iPhone الخاص بي‬

**Pull request closed without merging**
